zhangzy.lo: /usr/include/php/ext/zhangzy/zhangzy.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/usr/include/php/ext/zhangzy $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/include/php/ext/zhangzy/zhangzy.c -o zhangzy.lo 
$(phplibdir)/zhangzy.la: ./zhangzy.la
	$(LIBTOOL) --mode=install cp ./zhangzy.la $(phplibdir)

./zhangzy.la: $(shared_objects_zhangzy) $(ZHANGZY_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zhangzy) $(ZHANGZY_SHARED_LIBADD)

